### ISSUE TITLE
Data Request

### ISSUE THREAD

**Issue by surajpaib** [UM2ii/text2cohort#1]
Hi Team,

Thanks for sharing this work! A very interesting way to interact with IDC.

I plan to run experiments with a few pipelines I'm building myself, and it would be helpful to have the data you used to evaluate your approaches. While you mention it on the README, I can't seem to find it on the GitHub page it directs to.

Could you let me know how I can access this?

**Comment by adwaykanhere** [comment]
Hi @surajpaib, thanks for pointing this out! We have updated the data access on the README.
